import { Inter } from 'next/font/google';
import './globals.css';

export const metadata = {
  title: 'My Portofolio',
  description: 'Generated by Next.js',
}

const inter = Inter({ subsets: ['latin'], variable: '--font-inter' });

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={inter.variable}>
      <body className='font-sans'>{children}</body>
    </html>
  )
}
